
/**
* Datapacket. Packets are generated by data sources. 
*/
class DataPacket {

  /**
  * Construct data buffer.
  *
  * @param params with following keys:
  *   - buffer
  *     Raw data buffer.
  *   - timestamp
  *     Timestamp for this data packet.
  *   - tag
  *     Additional tag for this data packet.
  */
  constructor(params = {}) {
    this._buffer = params.hasOwnProperty('buffer') ?
      params.buffer : new Buffer();

    this._timestamp = params.hasOwnProperty('timestamp') ?
      params.timestamp : new Date().getTime();

    this._tag = params.hasOwnProperty('tag') ?
      params.tag : null;      
  }

  /**
  * Returns timestamp
  *
  * @return timestamp
  */
  getTimestamp() {
    return this._timestamp;
  }

  /**
  * Returns data buffer.
  *
  * @return buffer
  */
  getBuffer() {
    return this._buffer;
  }

  /**
  * Returns data packet tag.
  *
  * @return tag
  */
  getTag() {
    return this._tag;
  }
}

export default DataPacket;