
/**
* Datapacket. Packets are generated by data sources. 
*/
class DataPacket {

  /**
  * Construct data buffer.
  *
  * @param buffer
  *   Raw data buffer
  * @param options with following keys:
  *   - timestamp
  *     Timestamp for this data packet, default to current time
  *   - tag
  *     Additional tag for this data packet.
  */
  constructor(buffer, options = {}) {
    this._buffer = buffer;

    this._timestamp = options.hasOwnProperty('timestamp') ?
      options.timestamp : new Date().getTime();

    this._tag = options.hasOwnProperty('tag') ?
      options.tag : null;      
  }

  /**
  * Returns timestamp
  *
  * @return timestamp
  */
  getTimestamp() {
    return this._timestamp;
  }

  /**
  * Returns data buffer.
  *
  * @return buffer
  */
  getBuffer() {
    return this._buffer;
  }

  /**
  * Returns data packet tag.
  *
  * @return tag
  */
  getTag() {
    return this._tag;
  }
}

export default DataPacket;