'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* Datapacket. Packets are generated by data sources. 
*/
var DataPacket = function () {

  /**
  * Construct data buffer.
  *
  * @param buffer
  *   Raw data buffer
  * @param options with following keys:
  *   - timestamp
  *     Timestamp for this data packet, default to current time
  *   - tag
  *     Additional tag for this data packet.
  */
  function DataPacket(buffer) {
    var options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};

    _classCallCheck(this, DataPacket);

    this._buffer = buffer;

    this._timestamp = options.hasOwnProperty('timestamp') ? options.timestamp : new Date().getTime();

    this._tag = options.hasOwnProperty('tag') ? options.tag : null;
  }

  /**
  * Returns timestamp
  *
  * @return timestamp
  */


  _createClass(DataPacket, [{
    key: 'getTimestamp',
    value: function getTimestamp() {
      return this._timestamp;
    }

    /**
    * Returns data buffer.
    *
    * @return buffer
    */

  }, {
    key: 'getBuffer',
    value: function getBuffer() {
      return this._buffer;
    }

    /**
    * Returns data packet tag.
    *
    * @return tag
    */

  }, {
    key: 'getTag',
    value: function getTag() {
      return this._tag;
    }
  }]);

  return DataPacket;
}();

exports.default = DataPacket;